# Generated by Django 2.2 on 2020-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
