# Generated by Django 3.0 on 2019-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('R', 'ROCK'), ('B', 'BLUES'), ('J', 'JAZZ'), ('P', 'POP')], max_length=1)),
            ],
        ),
    ]
